-- 59411. 오랜 기간 보호한 동물(2)

SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_INS AS I RIGHT JOIN ANIMAL_OUTS AS O ON (I.ANIMAL_ID = O.ANIMAL_ID)
    WHERE I.ANIMAL_ID IS NOT NULL
    ORDER BY (I.DATETIME - O.DATETIME)
    LIMIT 2;